### PR TITLE
Adding resolver for akka-persistence-cassandra

### PR DESCRIPTION
**Pull request by pzapletal**
Hi,

had a issue `[warn] 	:: com.github.krasserm#akka-persistence-cassandra_2.11;0.4: not found` when pulled. Something like this may help.

Thanks for maintaining the project.

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks. Why would this be needed in the face of: https://bintray.com/search?query=akka-persistence-cassandra_2.11?

**Comment by pzapletal** [comment]
Haven't dug into it yet but seems like predefined repos were not used:
```
Cakes-MBP:reactive-flows petrzapletal$ sbt --version
sbt launcher version 0.13.5
Cakes-MBP:reactive-flows petrzapletal$ sbt clean compile
[info] Loading project definition from /Users/petrzapletal/Projects/pzapletal/reactive-flows/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to reactive-flows (in build file:/Users/petrzapletal/Projects/pzapletal/reactive-flows/)
[success] Total time: 0 s, completed Oct 29, 2015 12:25:38 AM
[info] Updating {file:/Users/petrzapletal/Projects/pzapletal/reactive-flows/}reactiveFlows...
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] Formatting 9 Scala sources {file:/Users/petrzapletal/Projects/pzapletal/reactive-flows/}reactiveFlows(compile) ...
[info] Resolving com.github.krasserm#akka-persistence-cassandra_2.11;0.4 ...
[warn] 	module not found: com.github.krasserm#akka-persistence-cassandra_2.11;0.4
[warn] ==== local: tried
[warn]   /Users/petrzapletal/.ivy2/local/com.github.krasserm/akka-persistence-cassandra_2.11/0.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/krasserm/akka-persistence-cassandra_2.11/0.4/akka-persistence-cassandra_2.11-0.4.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.krasserm#akka-persistence-cassandra_2.11;0.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.github.krasserm:akka-persistence-cassandra_2.11:0.4 (/Users/petrzapletal/Projects/pzapletal/reactive-flows/build.sbt#L25-41)
[warn] 		  +- de.heikoseeberger:reactive-flows_2.11:2.1.0
sbt.ResolveException: unresolved dependency: com.github.krasserm#akka-persistence-cassandra_2.11;0.4: not found
```

**Comment by hseeberger** [comment]
Do you have settings in `~/.sbt/0.13/???.sbt`?

**Comment by hseeberger** [comment]
Ah, wait a moment, you are using sbt launcher 0.13.5. Please upgrade to 0.13.9.

**Comment by pzapletal** [comment]
you're right, after updating to 0.13.9 it compiles well. Wondering, why I did't any warning because of `build.properties`. Anyway, thanks for help.

**Comment by hseeberger** [comment]
The sbt launcher is separate from the actual sbt libraries. The 0.13.5 launcher is able to pick up any other 0.13.x libraries.

**Pull request closed without merging**
